# Generated by Django 4.2.4 on 2023-08-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ('cname',), 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',), 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('pname',), 'verbose_name': 'product', 'verbose_name_plural': 'productss'},
        ),
    ]
